# Generated by Django 5.1.1 on 2024-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
